name: "Leslie's Site"
favicon: null
layout_spectrum: 0.8016667109914124
typography_spectrum: 0.11728376196697354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.26366496621631086
  lightness: 0.8300563097000122
  saturation: 0.5334349288605154
  rhythmicContrast: 0.6345032346434891
purpose: []
